### ISSUE TITLE
Ship Leaves While Players Are Alive

### ISSUE THREAD

**Issue by DavryH** [ANormalTwig/LC-LateCompany#10]
**Describe the bug**
The ship leaves while one player is still alive, leaving them stranded. The end player death count is one higher than the number of players in the lobby.

**To Reproduce**
1. Start a game with at least one other player.
2. Have all but one player die, leaving one survivor.
3. Ship will state that everyone is dead, then leave the survivor stranded.

**Expected behavior**
Ship stays when at least one player is alive and it is not past midnight.

**Additional context**
Tested with the bigger lobby mod. Have not tested without that mod.

**Comment by anormaltwig** [comment]
#6
