### ISSUE TITLE
(more company) when 4 players die, the rest are abandoned

### ISSUE THREAD

**Issue by MeMoTie** [ANormalTwig/LC-LateCompany#11]
**Describe the bug**
we have more company installed, when 4 people die, the ship auto departs and kills the remaining people.

**To Reproduce**
1. start game
2. have 4 players die
3. the ship autodeparts because "no response detected"

**Expected behavior**
4 players die and the game continues as there are still people alive.

**Comment by anormaltwig** [comment]
#6
