### ISSUE TITLE
Mod incompatibility report

### ISSUE THREAD

**Issue by PalpatineSWU** [ANormalTwig/LC-LateCompany#13]
The ship terminal system is bugged when LateCompany is ran along side the ReservedSlot series of mods.

>Running a bunch of mods off Thunderstore
>did tons of testing and refining to find and isolate error
>only happens when these are both enabled

What happens, like the issue of the bug.
The green text terminal that the player buys items from in the ship, when you walk up to it and interact with it the screen of the terminal is just black and you can't buy stuff. Happens in hosted and joined lobbies.

Not sure how to pull logs atm sorry.

**Comment by anormaltwig** [comment]
Can't reproduce and no logs provided.

**Comment by PalpatineSWU** [comment]
How do I pull logs?
