### ISSUE TITLE
BepInEx reporting that Late Company 1.0.4 targets a wrong version of BepInEx (5.4.22.0)

### ISSUE THREAD

**Issue by JoLouisLA11** [ANormalTwig/LC-LateCompany#17]
**Describe the bug**
BepInEx reporting that Late Company 1.0.4 targets a wrong version of BepInEx (5.4.22.0)
BepInEx 5.4.22.0 doesn't exist yet

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/ANormalTwig/LC-LateCompany/assets/73973706/3f440e46-e228-4b8b-afe5-716f9f763403)

**BepInEx Log**
Please include a link to BepInEx logs.

**Additional context**

**Comment by anormaltwig** [comment]
5.4.22 is the latest github version and it doesn't really matter.
