### ISSUE TITLE
Late Joiners are invisible

### ISSUE THREAD

**Issue by Qwazzy** [ANormalTwig/LC-LateCompany#2]
Used this mod today while hosting - 2 players joined mid missions during that time, and both were completely invisible except for their ranking nametag hovering in air. Items they held were also rendered fine, but the suit itself was invisible.

**Comment by Qwazzy** [comment]
I don't think it was a mod conflict - only other mods I had were Quick Restart (typing restart into chat to Fire everyone quickly) and ItemQuickSwitch (switching to hotbar with numbers 1-4). Also the LC API.

**Comment by anormaltwig** [comment]
Do you have steps I could use to reliably reproduce this? I don't think I've seen this happen in any of my testing.

**Comment by Qwazzy** [comment]
Apart from maybe trying it with the same modlist, I don't think so. It could have been a fluke of some kind.

Perhaps for now just keep the possibility in mind in case anyone else mentions the same issue. I might try the mod again another time, but for now I pulled it out of my host list since navigating with invisible players was problematic. 

I will add that it wasn't just on my end, they appeared invisible to the others in the lobby too, and if they died and respawned at the ship they would be visible again.

**Comment by Nebual** [comment]
I had an invisible ghost player (whose voice was tied to the ship's position at all times) too today **without any mods**, so I suspect that's a vanilla game bug. I found this mod while trying to see if there was a way for me to rejoin when I left to try to fix it heh.

Edit: I stand corrected, this mod does seem to introduce a 2nd type of ghost: the nametag, player name, anything they're carrying, and their voice origin works properly, its basically only their playermodel thats invisible. Which is a lot less broken than the vanilla ghost issue I'd seen twice before.

**Comment by anormaltwig** [comment]
It seems to happen when a player dies and leaves, and someone else takes their slot.

I'm not entire sure on how to fix it right now, I'll try to fix it eventually, if anyone has any ideas feel free to let me know or make your own pull request!

**Comment by Qwazzy** [comment]
Ah, true, in both my cases it was indeed someone dying, leaving, and another joining.

Wish I could help, though I’m no coder - but I hope someone figures it out. 

In the meantime, thanks for looking into it and making the mod!

**Comment by anormaltwig** [comment]
Might be fixed with ffe4b94af008513127abb57a1aa973fa1580199d

**Comment by mqopi** [comment]
> Might be fixed with [ffe4b94](https://github.com/ANormalTwig/LC-LateCompany/commit/ffe4b94af008513127abb57a1aa973fa1580199d)

still not fixed

**Comment by anormaltwig** [comment]
> > Might be fixed with [ffe4b94](https://github.com/ANormalTwig/LC-LateCompany/commit/ffe4b94af008513127abb57a1aa973fa1580199d)
> 
> still not fixed

Can you provide steps to reproduce? It's no longer occurring in my game.

**Comment by samuelbirocchi** [comment]
When I'm hosting it does not happen but people who join my game complains that other players are invisible.

![image](https://github.com/ANormalTwig/LC-LateCompany/assets/5590898/2fa7d77d-0754-4479-8ece-aaeb2190a3c6)
[LogOutput.log](https://github.com/ANormalTwig/LC-LateCompany/files/13540566/LogOutput.log)

**Comment by anormaltwig** [comment]
Everyone in the lobby needs the mod to prevent invisible players

**Comment by samuelbirocchi** [comment]
Do you think there is a way for the host to force load the players into the clients? Cause it would allow randos to join.
