### ISSUE TITLE
Flooded maps start at 100% flood for non-host players with LateCompany on

### ISSUE THREAD

**Issue by Kaillera** [ANormalTwig/LC-LateCompany#23]
When going to flooded maps, non-host players with LateCompany will either see the flood starts at 0% or 100%.

**Comment by Inioth** [comment]
Happens to me as host on the version 1.0.6, using 1.0.4 works fine

**Comment by NilaierMusic** [comment]
> Happens to me as host on the version 1.0.6, using 1.0.4 works fine

True, also works fine on Rainy maps too with 1.0.4
1.0.6 and 1.0.5 doesn't work though. 1.0.5 have different weather (host has Rainy, but client has Stormy or something else) while 1.0.6 just doesn't have any weather while host has one

**Comment by NilaierMusic** [comment]
> > Happens to me as host on the version 1.0.6, using 1.0.4 works fine
> 
> True, also works fine on Rainy maps too with 1.0.4 1.0.6 and 1.0.5 doesn't work though. 1.0.5 have different weather (host has Rainy, but client has Stormy or something else) while 1.0.6 just doesn't have any weather while host has one

In a new, 1.0.7 version, now weather just doesn't work, despite the fact that it should be on a moon. At least that's the case for Rainy and Flooded on LAN. No render, no mechanics.

**Comment by smartin1018** [comment]
I am also able to reproduce this bug

**Comment by Luna-the-dev** [comment]
I can also reproduce this bug. Anyone else also getting "DustClouds" as the new weather effect for the host when this happens as well?

**Comment by NilaierMusic** [comment]
> I can also reproduce this bug. Anyone else also getting "DustClouds" as the new weather effect for the host when this happens as well?

I'm pretty sure that 'DustClouds' isn't a new weather effect, it's just a hidden weather in the default game. I guess this mod just adds this effect back into the game as a visible text on the terminal.

**Comment by Hardeh** [comment]
We just had flood desync on latest 1.0.11 version today, on host it was normal and on non-host players it was 100% of water
