### ISSUE TITLE
(Suggestion) Some new options to prevent bugs

### ISSUE THREAD

**Issue by Fundryi** [ANormalTwig/LC-LateCompany#3]
Add 2 options/ways to join the game.

SpawnPlayerInstantly=true/false
Simply, if its false, player doesnt get spawned until next round is started but at least they are in the server.

AllowJoiningOnlyWhileShipInAir=true/false
Even more restricting but only allows new players to join if the ship is in the air... it still is better than having to restart the lobby completly and kicking 10+ players so one new can join :)

Right now this feels a bit buggy :o 

and last option that would probably be good is:

OnlyShowServerIfJoinable=true/false

So it only shows the server if they are actually able to join.

**Comment by Fundryi** [comment]
fyi: "ShipLobby" has added this kind of feature.

**Comment by anormaltwig** [comment]
which president is that

**Comment by anormaltwig** [comment]
I'll probably add an option to have players join as dead/spectator if the game is already started at some other time
