### ISSUE TITLE
Add Changelog every you fix/update

### ISSUE THREAD

**Issue by DHStyle541** [ANormalTwig/LC-LateCompany#32]
Hi, can you add the Changelog like what u fix? not only like this is.
![image](https://github.com/ANormalTwig/LC-LateCompany/assets/154591650/63552dee-4422-48dc-8668-87fc88910bdf)

i hate this is, because only like this is every update make me mad see every u update but still same problem. i using this is mod, cause ShipLobby no update anymore like abandon mod.

**Comment by UFTaco** [comment]
yes this is really needed

**Comment by Krampus69** [comment]
Yes please

**Comment by RizenSoulja** [comment]
Latest update was "Possible fix for weather Desync between clients". And yes, a change-log would be very much appreciated.
