### ISSUE TITLE
Please Remove the (Press Escape) Splash Screen

### ISSUE THREAD

**Issue by BenTech2** [ANormalTwig/LC-LateCompany#34]
I completely understand wanting to give credit to those who help develop the mod, but please remove the splash screen. I have a lot of friends who cant play this game because of this splash screen. the problem with it is the button that has been chosen to close the splash screen (ESCAPE) is a button that is not present on the SteamDeck even on the virtual keyboard meaning they cant get around it at all. or at the very least please change it to a different key or something.

Thanks

**Comment by anormaltwig** [comment]
This mod doesn't add a splash screen...

**Comment by BenTech2** [comment]
> This mod doesn't add a splash screen...

Sorry about that, after searching your code base you are correct. i was convinced this mod was causing the un-passable ESCAPE screen, but apparently it was a different mod. sorry about that
