### ISSUE TITLE
Players can't join after round started

### ISSUE THREAD

**Issue by NeboCode** [ANormalTwig/LC-LateCompany#36]
**Describe the bug**

Players can only join a game when in ship, this behavior was different before.

**To Reproduce**
1. Newest version of Lethal Company

**Expected behavior**

Allow players to join a game despite players being landed on a moon.

**Comment by anormaltwig** [comment]
Only joining while is the ship has been the default behavior for months, there's a config option you can change if you want to allow people to join on the moon.

**Comment by NeboCode** [comment]
Sorry to bother you. Not overly familiar with C#, where can I change this config option?

@ANormalTwig
