### ISSUE TITLE
Latejoin players might see others as "Unknown"s 

### ISSUE THREAD

**Issue by zoktiik** [ANormalTwig/LC-LateCompany#4]
Pretty much every latejoin player will see the others (probably not the host) as "Unknown" while the host can still see everyone's name. There might be conditions that would prevent this from happening, i.e. joining while the ship is in orbit, but people complain about this often when I am a latejoin host.

**Comment by anormaltwig** [comment]
I don't believe this is an issue with LateCompany, I do not set player names anywhere and player names are defaulted to 'Nameless' when there are no valid characters in someone's name and 'Player' as a fallback in the game.

**Comment by alkingshefo** [comment]
Did you find a solution to that? i am facing the same problem everyone is Unknown and bodyless when they join in orbit between days, old clients see the badge of new members and that's it, (clients) with the mod installed were able to see new players normally. should all clients install the mod not just the host? or could this be a compatibility issue with another mod?
