### ISSUE TITLE
Mod not working with LC v50

### ISSUE THREAD

**Issue by Nyxerian** [ANormalTwig/LC-LateCompany#40]
After the V50 update for LC, we've found that even inviting via steam invites are not working. I've checked with other players who stream the game and most of them are also having the same issue (out of 10 streamers asked, 8 had the issue.) 

Ensured game and all mods were up to date via steam and Thunderstore Mod Manager.
Attempted using new profile and reinstalling game and mods.
Trying to invite via game was not possible after start.
Tried to invite via Steam overlay after start also failed.

Will update report after getting screenshots.

**Comment by anormaltwig** [comment]
I am still able to invite players both through the steam overlay as well as the in game invite button in v50. You likely have at least one conflicting mod.

**Comment by Nyxerian** [comment]
Thank you, will do a scan through again and see which kod is conflicting.
