### ISSUE TITLE
Steam Friend List

### ISSUE THREAD

**Issue by ItsSourdough** [ANormalTwig/LC-LateCompany#41]
**Describe the bug**
When I go to invite friends from menu, the menu will pop up but i can't actually click on anything and then the list won't go away.

**To Reproduce**
1. Go to 'Invite Friends'
2. Steam list pops up
3. you won't be able to click on the list nor leave the list

**Screenshots**
![broken mod](https://github.com/ANormalTwig/LC-LateCompany/assets/168513141/f490721d-48b6-42c2-a8c0-43b642995b74)

**BepInEx Log**
Please include a link to BepInEx logs.

**Additional context**

**Comment by anormaltwig** [comment]
This sounds like an issue with steam overlay.
