### ISSUE TITLE
monitor only shows moon info

### ISSUE THREAD

**Issue by seasonedcurlys** [ANormalTwig/LC-LateCompany#7]

**Comment by Miruneko72** [comment]
This can be fixed by using "StartOfRound.Instance.SwitchMapMonitorPurpose(false);" on the StartOfRound singleton
However, this is client side and is not replicated to other players

**Comment by Miruneko72** [comment]
This bug also appears to occur when new players join mid-round, likely without the latecompany mod installed(?)
Still worth looking into as this plagues public lobbies, and breaks EVERYONE'S monitor in the process.

**Comment by ANormalTwig** [comment]
I have no idea what this issue is referring to
