### ISSUE TITLE
Ship leaving as soon as someone dies

### ISSUE THREAD

**Issue by CrusaderDae** [ANormalTwig/LC-LateCompany#9]
The ship leaves If one person dies when playing with only 2 players. When playing with 3 players, 2 people die and then the ship immediately leaves. The non host players then get stuck in the ship and on their screen it shows the dead screen. The host is also unable to start the match and has to quit the game to reset. It also says there are 1 more deaths than there actually is. For example, when two people are in a match it will say 3 deaths at the end which is not possible.

Here is an example of what happens: https://clips.twitch.tv/CaringPluckyBeanOSkomodo-gdTpBKYRfdLL-EY9

This only happens when LateCompany is installed.

**Comment by anormaltwig** [comment]
#6
